### ISSUE TITLE
OpenMDAO examples broken?

### ISSUE THREAD

**Issue by bbrelje** [byuflowlab/CCBlade.jl#14]
Hi there,

In a number of the OpenMDAO examples I get an error that af_from_files can't be imported on the julia side, e.g. when I run run_openmdao_ccblade.py, I get:

```
WARNING: replacing module _PyJuliaHelper.
Traceback (most recent call last):
  File "/root/pyjulia/src/julia/pseudo_python_cli.py", line 308, in main
    python(**vars(ns))
  File "/root/pyjulia/src/julia/pseudo_python_cli.py", line 59, in python
    scope = runpy.run_path(script, run_name="__main__")
  File "/root/miniconda3/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/root/miniconda3/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/root/miniconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "run_openmdao_ccblade.py", line 8, in <module>
    from ccblade.ccblade_jl import CCBladeGroup
  File "/root/CCBlade.jl/openmdao/python/ccblade/ccblade_jl.py", line 7, in <module>
    from julia.CCBlade import af_from_files
  File "/root/pyjulia/src/julia/core.py", line 260, in load_module
    raise ImportError("{} not found".format(juliapath))
ImportError: CCBlade.af_from_files not found
```

I'll poke around and see if I can fix it. Was this a name change to AlphaAF?

**Comment by bbrelje** [comment]
Ehh it's not just that, looks like a lot of things have broken. After sorting through the af_from_files deprecation in a number of places, I ended up with this.

```
RuntimeError: 'ccblade_group.ccblade_comp' <class JuliaImplicitComp>: Error calling solve_nonlinear(), <PyCall.jlwrap (in a Julia function called from Python)
JULIA: MethodError: no method matching CCBlade.Rotor(::Float64, ::Float64, ::Int64, ::Bool, ::Float64, ::Float64)
Closest candidates are:
  CCBlade.Rotor(::TF, ::TF, ::TI, !Matched::TF, ::TB, !Matched::T1, !Matched::T2, !Matched::T3, !Matched::T4) where {TF, TI, TB, T1<:Union{Nothing, CCBlade.MachCorrection}, T2<:Union{Nothing, CCBlade.ReCorrection}, T3<:Union{Nothing, CCBlade.RotationCorrection}, T4<:Union{Nothing, CCBlade.TipCorrection}} at /root/.julia/packages/CCBlade/AVeQe/src/CCBlade.jl:47
  CCBlade.Rotor(::Any, ::Any, ::Any; precone, turbine, mach, re, rotation, tip) at /root/.julia/packages/CCBlade/AVeQe/src/CCBlade.jl:60
Stacktrace:
 [1] solve_nonlinear!(::CCBladeOpenMDAOExample.CCBladeResidualComp{CCBlade.AlphaAF{Float64,String,FLOWMath.Akima{Array{Float64,1},Array{Float64,1},Float64}}}, ::PyDict{String,PyArray,true}, ::PyDict{String,PyArray,true}) at /root/CCBlade.jl/openmdao/src/openmdao.jl:203
 [2] solve_nonlinear!(::Int64, ::PyDict{String,PyArray,true}, ::PyDict{String,PyArray,true}) at /root/dev/OpenMDAO/src/OpenMDAO.jl:109
 [3] (::PyCall.FuncWrapper{Tuple{Integer,PyDict{String,PyArray,isdict} where isdict,PyDict{String,PyArray,isdict} where isdict},typeof(OpenMDAO.solve_nonlinear!)})(::Int64, ::Vararg{Any,N} where N; kws::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}) at /root/.julia/packages/PyCall/tqyST/src/callback.jl:56
 [4] (::PyCall.FuncWrapper{Tuple{Integer,PyDict{String,PyArray,isdict} where isdict,PyDict{String,PyArray,isdict} where isdict},typeof(OpenMDAO.solve_nonlinear!)})(::Int64, ::Vararg{Any,N} where N) at /root/.julia/packages/PyCall/tqyST/src/callback.jl:56
 [5] invokelatest(::Any, ::Any, ::Vararg{Any,N} where N; kwargs::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}) at ./essentials.jl:712
 [6] invokelatest(::Any, ::Any, ::Vararg{Any,N} where N) at ./essentials.jl:711
 [7] _pyjlwrap_call(::PyCall.FuncWrapper{Tuple{Integer,PyDict{String,PyArray,isdict} where isdict,PyDict{String,PyArray,isdict} where isdict},typeof(OpenMDAO.solve_nonlinear!)}, ::Ptr{PyCall.PyObject_struct}, ::Ptr{PyCall.PyObject_struct}) at /root/.julia/packages/PyCall/tqyST/src/callback.jl:28
 [8] pyjlwrap_call(::Ptr{PyCall.PyObject_struct}, ::Ptr{PyCall.PyObject_struct}, ::Ptr{PyCall.PyObject_struct}) at /root/.julia/packages/PyCall/tqyST/src/callback.jl:44
```

Is there an extant example somewhere showing optimization with CCBlade.jl, even if it's not in OpenMDAO?

**Comment by andrewning** [comment]
I only work on the pure Julia side of things, @dingraha created the openmdao wrapper.  I did make several breaking updates a few months ago.  Yes, for pure Julia, the docs details how to run CCBlade, and optimization examples you can find here: https://github.com/byuflowlab/ning2020-bem

**Comment by dingraha** [comment]
@bbrelje Are you interested in running the Julia version of CCBlade.jl (i.e. the code in `CCBlade.jl/src`) in OpenMDAO, or the Python version (`CCBlade.jl/openmdao/python/ccblade/ccblade_py.py`)? We wrote the Python version a while ago, but ended up focusing on the Julia version—the performance was much better.

The OpenMDAO examples haven't been updated in a while. I have many examples of how to use CCBlade.jl in an OpenMDAO `Problem` with the OpenMDAO.jl package, but I don't think I have them online anywhere at the moment. Let me know if you're interested in that.

**Comment by dingraha** [comment]
I put an example of a python package that uses CCBlade.jl in an OpenMDAO optimization here: https://github.com/dingraha/CCBladeOpenMDAOExamples
